name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [ windows-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@296fd3ccf8528660c91106efefe2364482f86d6f
      uses: NuGet/setup-nuget@v1.2.0

    - name: Build and Solution
      run: nuget restore "WLO Translator WPF.sln"
      
    - name: Build and Solution
      run: msbuild "WLO Translator WPF.sln"

    - name: Sign binary
      uses: lando/code-sign-action@v2
      with:
        file: /bin/Release
        certificate-data: ${{ secrets.WINDOZE_CERT_DATA }}
        certificate-password: ${{ secrets.WINDOZE_CERT_PASSWORD }}

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: /bin/Release
